name: Template Packaging Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
          versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2
      - name: Pack the template
        run: dotnet pack ./packageSettings.csproj -o ./artifacts/ /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} /p:RepositoryUrl=https://github.com/onelioubov/DotnetTemplateDemo
      - name: Push package to GitHub Registry
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.MyGet }} -s https://www.myget.org/F/demopackages/api/v2/package --no-symbols